run:
  tests: false
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  skip-files:
    - "relayer/chainproxy/thirdparty/*"
    - "relayer/chainproxy/grpc.go"

linters:
  disable-all: true
  #for list of linters and what they do: https://golangci-lint.run/usage/linters/
  enable:
    - depguard
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    #- unused we have a lot of unused code that we dont want to delete
    - forcetypeassert
    - goconst
    - gofmt
    - goimports
    - importas
    - ineffassign
    - nilnil
    - typecheck
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - text: "singleCaseSwitch"
      linters:
        - gocritic
    - text: "ifElseChain"
      linters:
        - gocritic
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false