build:
  binary: "lavad"
  main: "cmd/lavad"
accounts:
  - name: alice
    coins: ["200000000000ulava"]
  - name: bob
    coins: ["100000000ulava"]
  - name: user1
    coins: ["200000000ulava"]
  - name: user2
    coins: ["200000000ulava"]
  - name: user3
    coins: ["200000000ulava"]
  - name: user4
    coins: ["200000000ulava"]
  - name: servicer1
    coins: ["200000000ulava"]
  - name: servicer2
    coins: ["200000000ulava"]
  - name: servicer3
    coins: ["200000000ulava"]
  - name: servicer4
    coins: ["200000000ulava"]
  - name: servicer5
    coins: ["200000000ulava"]
  - name: servicer6
    coins: ["200000000ulava"]
  - name: servicer7
    coins: ["200000000ulava"]
  - name: servicer8
    coins: ["200000000ulava"]
  - name: servicer9
    coins: ["200000000ulava"]
  - name: servicer10
    coins: ["200000000ulava"]
validator:
  name: alice
  staked: "100000000000ulava"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000ulava"]
init:
  app:
    minimum-gas-prices: "0.000000001ulava"
genesis:
  chain_id: "lava"
  app_state:
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: "ulava"
      voting_params:
        voting_period: "3s"
    staking:
      params:
        bond_denom: "ulava"
    mint:
      params:
        mint_denom: "ulava"